all:
	Rscript -e 'rmarkdown::render("Chapter1.Rmd", output_format=c("html_document", "pdf_document", "word_document"))'


html:
	Rscript -e 'rmarkdown::render("Chapter1.Rmd", output_format="html_document")'


pdf:
	Rscript -e 'rmarkdown::render("Chapter1.Rmd", output_format="beamer_presentation")'

