---
title: "Final Project Outlines"
author: "Tyler J. Brough"
date: "April 16, 2019"
output:
  pdf_document: default
  html_document: default
---


## Final Project Outlines

Below are outlined the various options for the final project for the class. 


### Lamoureux & Lastrapes (JBES 1990) Monte Carlo Simulation Replication

In their paper _Persistence in variance, structural change, and the GARCH model_, Lamoureux and Lastrapes present a Monte Carlo simulation to demonstrate the
possibly overstated persistence in variance in GARCH-type models. Their strategy is to simulate from a process subject to structural change (e.g. "jumps" or regime
changes) and show how this effects the testing for the presence of GARCH effects. 

Your job in this project, should you choose to accept it, is to replicate their Monte Carlo simulation. Only their Monte Carlo simulation. There are not data requirements
for this project. The project highlights the importance of Monte Carlo methods as tools for model specification and investigation. A theme that we have developed deeply 
in this course. 


### Lamoureux & Lastrapes (JF 1990) GARCH vs. Volume Effects Replication

In their paper _Heteroskedasticity in Stock Return Data: Volume versus GARCH Effects_. Lamoureux and Lastrapes point out that when you include a ___"volume effect"___ term
in the basic GARCH(1,1) model that the other terms become insignificant. They take this to mean the GARCH model is proxying for a form of information flow that is captured
as a "GARCH effect".

Your job in this project is to reproduce their results using the MLE estimator that we have developed in class by adding the volume term to the estimation. You will need to 
add some components to the estimation, such as standard errors and test statistics. The data for the project will be historical prices for a stock of your choice for a five-year
period. Of course, you will also have to gather volume data for the stock.


### Bollen & Whaley 2005 Error-Correction Model

In their paper _Simulating Supply_ (Risk 2005), Bollen and Whaley present a novel Monte Carlo simulation from a pair of equations repesenting oil and natural gas returns and
futures basis. They estimate their equations via MLE and then use the estimated equations to simulate forward and replicate MGRM's 1-for-1 hedging strategy. 

Your job in this project, should you choose to accept it, is to replace their model equations with error-correction equations. You need to produce the same basic results but
with a neo-Austrian model that tends towards equilibrium but is allowed to deviate in certain periods. Notice that this matches Culp's & Miller's analysis a bit better than
Bollen and Whaley do in their model. 

Does it make a difference? Do you come to the same basic conclusion as BW do? Why or why not? 

Notice that this project utilizes the concepts of cointegration and error-correction, again concepts that we have developed deeply throughout this course. In addition, it 
employs the concept of the predictive density. It is also possible to re-interpret the analysis is a more neo-Austrian approach - an approach that Culp & Miller better matches
what MGRM were actually doing. 


### Hasbrouck (JF 1991) Replication

In his paper _Measuring the Information Content of Stock Trades_, Hasbrouck utilizes a Structural VAR model to model the causal impact of trades on stock prices. This project
builds on the concepts of multivariate time series and impulse response functions that have developed in the last portion of the class. 

Your job is to replicate Hasbrouck's results for a data set that I have provided.


## The Deliverable

The deliverable in all cases is a write-up that outlines the analysis, the conclusions, the code, and output of the modeling process. Your reports need not be longer than 5 or 6 pages.

